<?

$clickBankProduct = array(

//--begin popularity modifier to make the wow guides twice as popular
'<a href="http://2c97f0j8qnpajv8k-h0okksl3i.hop.clickbank.net/"><img src="http://www.zygorguides.com/img/midnight/levldr4.jpg" width="728" height="90" style="border-style:none;" /></a>',
'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="728" height="90" id="728x90_leveling" align="middle"> 	<param name="movie" value="http://www.ultimatewowguide.com/banners/leveling/728x90_leveling.swf?clickTAG=http://196f8wkwpdo4a2agow9q5kcoam.hop.clickbank.net/" /> 	<param name="quality" value="high" /> 	<param name="bgcolor" value="#ffffff" /> 	<param name="play" value="true" /> 	<param name="loop" value="true" /> 	<param name="wmode" value="window" /> 	<param name="scale" value="showall" /> 	<param name="menu" value="true" /> 	<param name="devicefont" value="false" /> 	<param name="salign" value="" /> 	<param name="allowScriptAccess" value="always" /> <!--[if !IE]>--> 	<object type="application/x-shockwave-flash" data="http://www.ultimatewowguide.com/banners/leveling/728x90_leveling.swf?clickTAG=http://196f8wkwpdo4a2agow9q5kcoam.hop.clickbank.net/" width="728" height="90"> 		<param name="movie" value="http://www.ultimatewowguide.com/banners/leveling/728x90_leveling.swf?clickTAG=http://196f8wkwpdo4a2agow9q5kcoam.hop.clickbank.net/" /> 		<param name="quality" value="high" /> 		<param name="bgcolor" value="#ffffff" /> 		<param name="play" value="true" /> 		<param name="loop" value="true" /> 		<param name="wmode" value="window" /> 		<param name="scale" value="showall" /> 		<param name="menu" value="true" /> 		<param name="devicefont" value="false" /> 		<param name="salign" value="" /> 		<param name="allowScriptAccess" value="always" /> 	<!--<![endif]--> 	<a href="http://www.adobe.com/go/getflash"> 		<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /> 	</a> 	<!--[if !IE]>--> 	</object> 	<!--<![endif]--> </object>',
//--end popularity modifier



'<a href="http://2c97f0j8qnpajv8k-h0okksl3i.hop.clickbank.net/"><img src="http://www.zygorguides.com/img/midnight/levldr4.jpg" width="728" height="90" style="border-style:none;" /></a>',
'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" width="728" height="90" id="728x90_leveling" align="middle"> 	<param name="movie" value="http://www.ultimatewowguide.com/banners/leveling/728x90_leveling.swf?clickTAG=http://196f8wkwpdo4a2agow9q5kcoam.hop.clickbank.net/" /> 	<param name="quality" value="high" /> 	<param name="bgcolor" value="#ffffff" /> 	<param name="play" value="true" /> 	<param name="loop" value="true" /> 	<param name="wmode" value="window" /> 	<param name="scale" value="showall" /> 	<param name="menu" value="true" /> 	<param name="devicefont" value="false" /> 	<param name="salign" value="" /> 	<param name="allowScriptAccess" value="always" /> <!--[if !IE]>--> 	<object type="application/x-shockwave-flash" data="http://www.ultimatewowguide.com/banners/leveling/728x90_leveling.swf?clickTAG=http://196f8wkwpdo4a2agow9q5kcoam.hop.clickbank.net/" width="728" height="90"> 		<param name="movie" value="http://www.ultimatewowguide.com/banners/leveling/728x90_leveling.swf?clickTAG=http://196f8wkwpdo4a2agow9q5kcoam.hop.clickbank.net/" /> 		<param name="quality" value="high" /> 		<param name="bgcolor" value="#ffffff" /> 		<param name="play" value="true" /> 		<param name="loop" value="true" /> 		<param name="wmode" value="window" /> 		<param name="scale" value="showall" /> 		<param name="menu" value="true" /> 		<param name="devicefont" value="false" /> 		<param name="salign" value="" /> 		<param name="allowScriptAccess" value="always" /> 	<!--<![endif]--> 	<a href="http://www.adobe.com/go/getflash"> 		<img src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif" alt="Get Adobe Flash player" /> 	</a> 	<!--[if !IE]>--> 	</object> 	<!--<![endif]--> </object>',
'<a href="http://cc79dvl91jrzjw08scm27ro8f6.hop.clickbank.net/" target="_self"><img src="http://flightprosim.com/images/banner_1-468x60.gif" alt="FlightProSim.com" style="border-style:none;" /></a>',
'<a href="http://94d516s5-qfaer395amfk3lr5r.hop.clickbank.net/"><img src="http://www.proflightsimulator.com/images/banners/468x60-flightbanner.gif" width="468" height="60" border="0" style="border-style:none;"></a>'
);

echo $clickBankProduct[array_rand($clickBankProduct)];


?>